(ns dj.web.sse-test
  "Layer 3, the **envelopes**: `dj.web.sse` diffed against
  `starfederation.datastar.clojure.api.sse` over the shared matrix in
  `dj.web.wire-matrix` (which explains the method).

  Extraction stages asserted here: **1** (frame assembly, `write-event!`, `write-comment!`),
  the half of **2** that landed on this side of the boundary
  (`normalize-event-opts`, which was the SDK's private `rework-options` until
  owning layer 2 moved the entry point past it), and **5** — layer 5, the
  response headers.

  the header extraction is the first one whose central function has **no oracle**:
  `acceptable-encoding?` is asserted against RFC 9110 rather than against the
  SDK, because the SDK never asks the question. That is not a gap in the method,
  it is what the method is for — the differential pins everything the SDK does,
  and what is left over is the capability owning the layer bought.

  Also here: the byte-level check on the adapter's write path, because that is
  where this layer meets a real `OutputStream`."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [dj.web.datastar :as ds]
            [dj.web.sse :as sse]
            [dj.web.wire-matrix :as m]
            [starfederation.datastar.clojure.adapter.common :as ac]
            [starfederation.datastar.clojure.api.common :as sdk-common]
            [starfederation.datastar.clojure.api.elements :as sdk-elements]
            [starfederation.datastar.clojure.api.signals :as sdk-signals]
            [starfederation.datastar.clojure.api.sse :as sdk-sse]
            [starfederation.datastar.clojure.consts :as sdk-consts])
  (:import [java.io ByteArrayOutputStream Writer]
           [java.nio.charset StandardCharsets]))

;; -----------------------------------------------------------------------------
;; Layer 1 — the SSE literals
;; -----------------------------------------------------------------------------

(deftest sse-literals-match-the-sdk
  (testing "the option keywords and default `write-event!` reads are the SDK's"
    ;; The whole the literal-compatibility check idea in three assertions. `consts.clj` upstream carries
    ;; "auto-generated by Datastar. DO NOT EDIT" — the literals are generated
    ;; from the spec across every language SDK at once, while ours are
    ;; hand-written. Keeping the jar in :deps turns it from a dependency into a
    ;; spec tracker: a `clj -Sforce -M:test` after an SDK bump tells us the wire
    ;; moved, here, instead of in a browser.
    (is (= sdk-common/id sse/id))
    (is (= sdk-common/retry-duration sse/retry-duration))
    (is (= sdk-consts/default-sse-retry-duration sse/default-retry-duration))))

;; -----------------------------------------------------------------------------
;; the framing extraction — frame assembly
;; -----------------------------------------------------------------------------

(defn- sdk-frame [event-type data-lines opts]
  (str (sdk-sse/write-event! (StringBuilder.) event-type data-lines opts)))

(defn- our-frame [event-type data-lines opts]
  (str (sse/write-event! (StringBuilder.) event-type data-lines opts)))

(deftest frame-assembly-matches-the-sdk-on-the-id-retry-matrix
  (testing "event:/id:/retry:/data:/terminator, over every id x retry x shape"
    (let [d (m/diffs m/frame-cases
                     #(our-frame (:event-type %) (:data-lines %) (:opts %))
                     #(sdk-frame (:event-type %) (:data-lines %) (:opts %)))]
      (is (empty? d) (m/report d)))))

(deftest frame-assembly-matches-the-sdk-on-real-data-lines
  (testing "3,888 element payloads, framed"
    ;; Data lines come from the SDK here even though we now own that layer too —
    ;; on purpose. This is a layer-3 test, and feeding it layer-2 output from
    ;; the oracle keeps a bug in one layer from hiding a bug in the other.
    (let [d (m/diffs m/element-cases
                     #(our-frame sdk-consts/event-type-patch-elements
                                 (sdk-elements/->patch-elements (:elements %) (:opts %))
                                 {})
                     #(sdk-frame sdk-consts/event-type-patch-elements
                                 (sdk-elements/->patch-elements (:elements %) (:opts %))
                                 {}))]
      (is (empty? d) (m/report d))))
  (testing "and the signals payloads"
    (let [d (m/diffs m/signals-cases
                     #(our-frame sdk-consts/event-type-patch-signals
                                 (sdk-signals/->patch-signals (:signals %) (:opts %))
                                 {})
                     #(sdk-frame sdk-consts/event-type-patch-signals
                                 (sdk-signals/->patch-signals (:signals %) (:opts %))
                                 {}))]
      (is (empty? d) (m/report d)))))

(deftest the-frame-is-what-we-think-it-is
  (testing "the oracle agreeing is not the same as the wire being right"
    ;; Two implementations can agree and both be wrong. One literal assertion,
    ;; written from the SSE spec rather than from either implementation, is what
    ;; keeps the differential tests from being self-referential.
    (is (= "event: datastar-patch-elements\ndata: elements <div>x</div>\n\n"
           (our-frame "datastar-patch-elements" ["elements <div>x</div>"] {})))
    (is (= (str "event: datastar-patch-elements\n"
                "id: e1\n"
                "retry: 500\n"
                "data: selector #x\n"
                "data: elements a\n"
                "data: elements b\n"
                "\n")
           (our-frame "datastar-patch-elements"
                      ["selector #x" "elements a" "elements b"]
                      {sse/id "e1" sse/retry-duration 500}))))
  (testing "an event with no data lines is still a terminated frame"
    (is (= "event: datastar-patch-elements\n\n"
           (our-frame "datastar-patch-elements" [] {})))))

(deftest write-event-returns-the-appendable
  ;; The SDK's does (it is a `doto`), and `->send`'s temp-buffer path relies on
  ;; it to `str` the builder in one expression.
  (let [sb (StringBuilder.)]
    (is (identical? sb (sse/write-event! sb "e" [] {})))))

;; -----------------------------------------------------------------------------
;; the wire extraction's other half — option normalization, now ours
;; -----------------------------------------------------------------------------

(def ^:private sdk-rework
  "`sse/rework-options` is **private** and runs inside `sse/send-event!`, i.e.
  upstream of the generator's `p/send-event!`. It was therefore upstream of us
  too, for exactly as long as calls entered through `d*/patch-elements!`. the wire extraction
  moved the entry point to `ds/patch-elements!`, so it is ours now — and this is
  the oracle for it."
  @#'sdk-sse/rework-options)

(deftest normalize-event-opts-matches-the-private-sdk-rework
  (testing "over the full id x retry matrix"
    ;; The trap this slice was one step away from, now landed. Had we moved the
    ;; entry point without bringing the normalization along, blank ids and
    ;; redundant `retry: 1000` lines would have reached the wire and no test
    ;; that goes through a facade would have seen it — because we are the
    ;; facade now.
    (let [cases (vec (for [[ik id]    m/ids
                           [rk retry] m/retries]
                       {:label {:id ik :retry rk}
                        :opts  (-> {}
                                   (m/assoc-some sdk-common/id id)
                                   (m/assoc-some sdk-common/retry-duration retry))}))
          ;; `false` for id/retry is what normalization *produces*; feeding it
          ;; back in is a type error on both sides, so those rows are skipped.
          cases (filterv #(and (not= :dropped (-> % :label :id))
                               (not= :dropped (-> % :label :retry)))
                         cases)
          d (m/diffs cases
                     #(sse/normalize-event-opts (:opts %))
                     #(sdk-rework (:opts %)))]
      (is (empty? d) (m/report d)))))

(deftest normalize-event-opts-drop-rules
  (testing "what the rules are, stated rather than inherited"
    ;; Note the value: a dropped option comes back **`false`, not `nil`**, and
    ;; both keys are always present — normalization builds a fresh 2-key map
    ;; with `(and (keep? v) v)`. So the contract `write-event!` actually has to
    ;; honour is "emit when truthy", never `(contains? opts id)` and never
    ;; `(some? (get opts id))`; either of those puts `id: false` on the wire on
    ;; the *default* path. This assertion is here because the first version of
    ;; it guessed `nil` and was wrong.
    (is (= {sse/id false sse/retry-duration false} (sse/normalize-event-opts {}))
        "defaults: no id, and 1000ms retry is Datastar's default")
    (is (false? (sse/id (sse/normalize-event-opts {sse/id ""})))
        "a blank id is dropped, not emitted as `id: `")
    (is (false? (sse/id (sse/normalize-event-opts {sse/id "   "})))
        "and whitespace-only counts as blank")
    (is (= "e1" (sse/id (sse/normalize-event-opts {sse/id "e1"}))))
    (is (false? (sse/retry-duration (sse/normalize-event-opts {sse/retry-duration 0})))
        "0 means 'no retry line', not 'retry immediately'")
    (is (false? (sse/retry-duration (sse/normalize-event-opts {sse/retry-duration 1000})))
        "the default duration is never put on the wire")
    (is (= 500 (sse/retry-duration (sse/normalize-event-opts {sse/retry-duration 500})))))
  (testing "and composed with our framing it drops the lines, not just the keys"
    (is (= "event: e\n\n" (our-frame "e" [] (sse/normalize-event-opts {sse/id ""}))))
    (is (= "event: e\n\n" (our-frame "e" [] (sse/normalize-event-opts
                                             {sse/retry-duration 1000}))))
    (is (= "event: e\nid: e1\n\n" (our-frame "e" [] (sse/normalize-event-opts
                                                     {sse/id "e1"})))))
  (testing "a wrong-typed option is named at the call site"
    (is (thrown? AssertionError (sse/normalize-event-opts {sse/id :not-a-string})))
    (is (thrown? AssertionError (sse/normalize-event-opts {sse/retry-duration "500"})))))

;; -----------------------------------------------------------------------------
;; The capability owning layer 3 buys
;; -----------------------------------------------------------------------------

(deftest comment-frames
  (testing "a heartbeat is ten bytes and not an event"
    (let [frame (str (sse/write-comment! (StringBuilder.) "ping"))]
      (is (= ": ping\n\n" frame))
      ;; The reason this cannot be done through the SDK: every path into a
      ;; generator goes through `p/send-event!`, which writes `event: <type>`
      ;; before anything else, so the cheapest SDK heartbeat is a no-op
      ;; `patch-signals!` — ~40 bytes and a real client-side event.
      (is (not (str/includes? frame "event:")))
      (is (< (count frame)
             (count (our-frame sdk-consts/event-type-patch-signals
                               (sdk-signals/->patch-signals "{}" {})
                               {})))))))

;; -----------------------------------------------------------------------------
;; the header extraction — layer 5, the response headers
;; -----------------------------------------------------------------------------

(defn- sdk-headers
  "The oracle, called the way the SDK is shaped: the coding reaches `ac/headers`
  only as a property of a write profile, never as an argument. Building a
  one-key profile here is not a contrivance — it is the SDK's *only* way to ask
  for a `Content-Encoding`, and that is the constraint the header extraction is about."
  [request encoding extra]
  (ac/headers request {ac/write-profile {ac/content-encoding encoding}
                       :headers         extra}))

(deftest headers-match-the-sdk-on-every-protocol-and-coding
  (testing "90 cases: 6 protocols x 3 codings x 5 caller-header shapes"
    (let [d (m/diffs m/sse-header-cases
                     #(sse/headers (:request %) (:encoding %) (:extra %))
                     #(sdk-headers (:request %) (:encoding %) (:extra %)))]
      (is (empty? d) (m/report d)))))

(defn- naive-keep-alive-headers
  "What you write if you implement the ADR's text and remember the one exception
  everybody remembers: `Connection: keep-alive` everywhere **except HTTP/2**,
  named explicitly. Kept executable as a negative control, for the same reason
  `naive-split` is in `wire-test`."
  [request encoding extra]
  (-> sse/base-headers
      (cond-> (not= "HTTP/2" (:protocol request)) (assoc "Connection" "keep-alive")
              encoding (assoc "Content-Encoding" encoding))
      (merge extra)))

(deftest the-keep-alive-rule-is-below-1-1-not-at-it
  (testing "naming HTTP/2 instead of ordering versions diverges on 1.1 AND 3"
    ;; The rule this layer is worth owning for. `Connection` is redundant from
    ;; HTTP/1.1 on (persistent is the default) and FORBIDDEN in HTTP/2 — RFC
    ;; 9113 §8.2.2 makes it a connection-specific field a peer must treat as
    ;; malformed, and RFC 9114 §4.2 says the same for HTTP/3.
    ;;
    ;; HTTP/1.1 is the divergence this control was written to produce: the ADR
    ;; says set the header *for* 1.1, and the SDK deliberately doesn't. **HTTP/3
    ;; was not predicted** — it fell out of running the control, exactly as the
    ;; third `split-lines` divergence did in `wire-test`. That is the finding: a
    ;; correct-looking implementation encodes the exception it remembers by
    ;; name, and is then wrong for every version that ships after it is written.
    ;; `(neg? (compare protocol "HTTP/1.1"))` is not a terser spelling of the
    ;; same rule — it is a rule about ordering, so it covers versions that did
    ;; not exist when it was written.
    (let [d (m/diffs m/sse-header-cases
                     #(naive-keep-alive-headers (:request %) (:encoding %) (:extra %))
                     #(sdk-headers (:request %) (:encoding %) (:extra %)))]
      (is (= #{:http-1.1 :http-3} (into #{} (map (comp :protocol :label)) d))
          (str "the negative control found: " (pr-str (mapv :label d))))))
  (testing "and nil sorts below every protocol, so an absent one keeps alive"
    ;; `compare` does this, not the explicit nil? clause — worth an assertion
    ;; because the redundancy is only safe in one direction.
    (is (= "keep-alive" (get (sse/headers nil nil nil) "Connection")))
    (is (= "keep-alive" (get (sse/headers {:protocol "HTTP/1.0"} nil nil) "Connection")))
    (is (nil? (get (sse/headers {:protocol "HTTP/1.1"} nil nil) "Connection")))
    (is (nil? (get (sse/headers {:protocol "HTTP/2"} nil nil) "Connection")))
    (is (nil? (get (sse/headers {:protocol "HTTP/3"} nil nil) "Connection"))
        "a version the rule predates, which is the reason it is a comparison")))

(deftest the-headers-are-what-we-think-they-are
  (testing "written from the spec, not from either implementation"
    ;; Two implementations can agree and both be wrong.
    (is (= {"Cache-Control" "no-cache"
            "Content-Type"  "text/event-stream"
            "Connection"    "keep-alive"}
           (sse/headers {:protocol "HTTP/1.0"} nil nil))))
  (testing "the content type is bare — no charset parameter"
    ;; `text/event-stream` is UTF-8 by definition in the HTML spec, and
    ;; `http-test/sse-round-trip` asserts exact equality on the value.
    (is (= "text/event-stream" (get sse/base-headers "Content-Type"))))
  (testing "the caller's headers are merged last and win"
    (is (= "no-store" (get (sse/headers nil nil {"Cache-Control" "no-store"})
                           "Cache-Control")))
    (is (= "close" (get (sse/headers nil nil {"Connection" "close"}) "Connection"))))
  (testing "and Content-Encoding appears only when there is a coding"
    (is (nil? (get (sse/headers nil nil nil) "Content-Encoding")))
    (is (= "gzip" (get (sse/headers nil "gzip" nil) "Content-Encoding")))))

;; -----------------------------------------------------------------------------
;; The capability owning layer 5 buys
;; -----------------------------------------------------------------------------

(deftest acceptable-encoding-follows-rfc-9110
  ;; No differential here: the SDK has no counterpart, which is the whole point
  ;; — `ac/headers` never reads `Accept-Encoding` at all. So these are written
  ;; from RFC 9110 §12.5.3 directly, like `the-headers-are-what-we-think-they-are`
  ;; above and unlike everything with an oracle behind it.
  (let [accepts? (fn [v] (sse/acceptable-encoding?
                          {:headers (cond-> {} v (assoc "accept-encoding" v))}
                          "gzip"))]
    (testing "silence is permission — the plan had this one backwards"
      ;; the extraction design called the SDK's behaviour \"gzips a client that didn't ask\".
      ;; Not asking is not refusing: with no Accept-Encoding field, any content
      ;; coding is acceptable. The defect is narrower than the plan stated.
      (is (true? (accepts? nil)))
      (is (true? (sse/acceptable-encoding? nil "gzip")) "nil request too")
      (is (true? (sse/acceptable-encoding? {} "gzip"))))

    (testing "the three spellings of refusal"
      (is (false? (accepts? "identity")) "listed something else, no wildcard")
      (is (false? (accepts? "gzip;q=0")) "named and rejected")
      (is (false? (accepts? "")) "empty field: no coding at all is wanted"))

    (testing "acceptance"
      (is (true? (accepts? "gzip")))
      (is (true? (accepts? "gzip, deflate, br")))
      (is (true? (accepts? "br;q=1.0, gzip;q=0.5")) "a low q is still a yes")
      (is (true? (accepts? "gzip;q=0.001")) "we rank nothing — only q=0 refuses"))

    (testing "the wildcard stands in for anything unnamed"
      (is (true? (accepts? "*")))
      (is (false? (accepts? "*;q=0")))
      (is (true? (accepts? "gzip, *;q=0")) "named beats the wildcard")
      (is (false? (accepts? "identity, *;q=0"))))

    (testing "the parsing details that a `str/includes?` would get wrong"
      ;; Which is the point of parsing at all: `(str/includes? v \"gzip\")` says
      ;; yes to `gzip;q=0`, and yes to `x-gzip`, which is a different coding.
      (is (true?  (accepts? " GZIP ")) "case-insensitive, whitespace-tolerant")
      (is (true?  (accepts? "gzip ; q=0.7")) "spaces around the parameter")
      (is (false? (accepts? "x-gzip")) "a different coding, not a substring match")
      (is (true?  (accepts? "gzip;q=bogus")) "an unreadable q defaults to 1"))

    (testing "and it is asked about the coding, not told about gzip"
      (is (true? (sse/acceptable-encoding? {:headers {"accept-encoding" "br"}} "br")))
      (is (false? (sse/acceptable-encoding? {:headers {"accept-encoding" "br"}} "gzip"))))))

(deftest a-refused-coding-downgrades-the-profile-not-just-the-header
  (testing "the header and the stream wrapping stay two halves of one decision"
    ;; Suppressing the header alone would be worse than the bug: the profile
    ;; would still wrap the socket in a GZIPOutputStream, so the client would get
    ;; gzip bytes with nothing declaring them. `->sse-response` therefore rewrites
    ;; the opts it hands the generator, and reads the header off the same value.
    (let [request (fn [accept-encoding]
                    {:request-method :get
                     :protocol       "HTTP/1.1"
                     :headers        (cond-> {}
                                       accept-encoding
                                       (assoc "accept-encoding" accept-encoding))})
          opts    {ac/write-profile ac/gzip-profile ac/on-open (fn [_sse] nil)}
          profile #(@#'ds/negotiated-write-profile (request %) opts)
          header  #(get (:headers (ds/->sse-response (request %) opts))
                        "Content-Encoding")]
      (testing "a client that refused gets neither the header nor the gzip"
        (is (= ac/basic-profile (profile "identity")))
        (is (nil? (header "identity"))))
      (testing "a client that accepted gets both"
        (is (= ac/gzip-profile (profile "gzip")))
        (is (= "gzip" (header "gzip"))))
      (testing "and silence is still permission, so nothing changes for a browser"
        (is (= ac/gzip-profile (profile nil)))
        (is (= "gzip" (header nil))))
      (testing "a profile with no coding is never touched"
        ;; The refusal path must not fire for the profile everything actually
        ;; uses — there is nothing to negotiate about an uncompressed stream.
        (is (= ac/basic-profile
               (@#'ds/negotiated-write-profile (request "identity")
                                               {ac/on-open (fn [_sse] nil)})))))))

;; -----------------------------------------------------------------------------
;; The swap point: the adapter's write path, byte for byte
;; -----------------------------------------------------------------------------

(defn- bytes-via-sdk-profile
  "What `->send` used to emit: the profile's own `ac/write!`."
  [profile event-type data-lines opts]
  (let [baos    (ByteArrayOutputStream.)
        wrapped ((ac/wrap-output-stream profile) baos)]
    ((ac/write! profile) wrapped event-type data-lines opts)
    (.flush ^Writer wrapped)
    (.toByteArray baos)))

(defn- bytes-via-our-send
  "What `->send` emits now: our buffering decision plus `sse/write-event!`."
  [profile event-type data-lines opts]
  (let [baos  (ByteArrayOutputStream.)
        send! (@#'ds/->send baos {ac/write-profile profile})]
    (send! event-type data-lines opts)
    (.toByteArray baos)))

(deftest send-path-is-byte-identical-to-the-sdk-profiles
  (testing "both stock uncompressed profiles, over the full frame matrix"
    ;; This is what makes the `->send` change a *swap* rather than a rewrite:
    ;; we stopped reading the profile's `write!` key and now decide buffering
    ;; from the wrapped stream, so the buffered profile takes the write-through
    ;; branch that the SDK reserves for its gzip variant. Same bytes either way
    ;; — which is precisely the claim under test.
    (doseq [[pname profile] (array-map :basic    ac/basic-profile
                                       :buffered ac/buffered-writer-profile)]
      (let [d (m/diffs m/frame-cases
                       #(String. ^bytes (bytes-via-our-send profile (:event-type %)
                                                            (:data-lines %) (:opts %))
                                 StandardCharsets/UTF_8)
                       #(String. ^bytes (bytes-via-sdk-profile profile (:event-type %)
                                                               (:data-lines %) (:opts %))
                                 StandardCharsets/UTF_8))]
        (is (empty? d) (str pname " profile: " (m/report d))))))
  (testing "UTF-8 survives the buffering decision"
    ;; The two branches encode at different moments (String -> writer, versus
    ;; field by field into a BufferedWriter), so a multi-byte character is worth
    ;; asserting at the byte level rather than trusting the String comparison.
    (doseq [profile [ac/basic-profile ac/buffered-writer-profile]]
      (is (= (seq (.getBytes "event: e\ndata: elements <p>an em — dash</p>\n\n"
                             StandardCharsets/UTF_8))
             (seq (bytes-via-our-send profile "e"
                                      ["elements <p>an em — dash</p>"] {})))))))
