(ns dj.web.sse
  "**Envelopes.** The Server-Sent Events wire format — `event:`, `id:`, `retry:`,
  `data:`, the blank-line terminator, and the rules that decide which of those
  lines exist. It knows how to put a line on the wire and nothing whatsoever
  about what the line *means*.

  It deliberately lives outside `dj.web.datastar`:

      semantic op          data lines              frame bytes          socket
      patch-elements  ->   [\"mode append\"    ->   event: ...\\n     ->   OutputStream
      html + opts          \"elements <div>\"]      data: mode append\\n
                                                  data: elements ...\\n
                                                  \\n
      layer 2              layer 3 (HERE)          layer 4
      datastar.wire        dj.web.sse         dj.web.datastar
      \"the letters\"        \"the envelopes\"         transport

  The letters are Datastar's; the envelopes are the WHATWG HTML spec's, shared
  with every other SSE producer on the internet. Keeping them in separate
  namespaces makes that difference structural rather than a comment: **nothing
  here may require `starfederation.*` or `dj.web.datastar.*`.** If it ever
  needs to, a layer boundary was drawn in the wrong place. It is also pure —
  strings and vectors in, appends out; no protocol, no IO decisions, no lock.

  The interface to layer 2 is a plain vector of strings, which is why either
  layer can independently be ours or the SDK's with no shim between them. The
  interface to layer 4 is an `Appendable`.

  Layer **5** — the response headers — lives here too, for the same reason: an
  SSE response's headers are the HTML spec's, not Datastar's. They are the start
  of the same stream `write-event!` writes into, so they belong in the namespace
  that owns the stream's format rather than in the transport that opens it.

  Three behaviours deliberately differ from the official SDK: `write-event!`
  preserves append failures instead of wrapping them, `write-comment!` adds
  heartbeat frames, and `acceptable-encoding?` owns HTTP content negotiation.
  Differential tests compare every function with an SDK counterpart."
  (:require [clojure.string :as str])
  (:import [java.lang Appendable]))

;; -----------------------------------------------------------------------------
;; Option keys and defaults
;; -----------------------------------------------------------------------------
;;
;; These three SSE literals are pinned to the SDK by
;; `sse-test/sse-literals-match-the-sdk`. Upstream's `consts.clj` carries
;; "auto-generated by Datastar. DO NOT EDIT" — the literals are generated from
;; the spec across every language SDK at once, while ours are hand-written. So a
;; `clj -Sforce -M:test` after an SDK bump tells us the wire moved, here, rather
;; than in a browser.

(def id
  "SSE event option: the `id:` line's value. A non-blank String, or absent."
  :d*.sse/id)

(def retry-duration
  "SSE event option: the `retry:` line's value, in ms."
  :d*.sse/retry-duration)

(def default-retry-duration
  "The reconnect delay the client already assumes, so putting it on the wire
  says nothing. `normalize-event-opts` drops it for that reason.

  Note this is **Datastar's** default, not the SSE spec's — the spec leaves the
  reconnection time to the user agent (browsers use ~3 s). The value lives here
  rather than with the letters because the only thing that reads it is the rule
  that suppresses the `retry:` line."
  1000)

;; -----------------------------------------------------------------------------
;; Option normalization
;; -----------------------------------------------------------------------------

(defn normalize-event-opts
  "Reduce a caller's option map to exactly the two keys a frame can carry, with
  each one either its value or **`false`**:

      {}                        => {id false, retry-duration false}
      {id \"e1\"}                 => {id \"e1\", retry-duration false}
      {retry-duration 500}      => {id false, retry-duration 500}

  The drop rules — an empty `id` and a `retry` of 0 or the default 1000 produce
  no line — are the SDK's, where they live in the **private**
  `sse/rework-options` and run inside `sse/send-event!`, i.e. *upstream* of the
  generator's `p/send-event!`.

  That placement is why this function is here at all, and it is the sharpest
  trap in the whole reimplementation plan (the extraction design). While calls still
  entered through `d*/patch-elements!`, the SDK normalized for us and
  `write-event!` never saw a raw option map. **the wire extraction moved the entry point to
  `dj.web.datastar/patch-elements!`**, so the rework became ours on that
  day — and had we not noticed, blank ids and redundant `retry: 1000` lines
  would have started appearing on the wire with nothing to catch them, because
  no test that goes through the facade exercises the path the facade owns.

  `false` rather than `nil` is not an accident of ours; it is what the SDK
  produces (`(and (keep? v) v)` over a freshly built 2-key map) and what
  `write-event!`'s \"emit when truthy\" contract is written against. Returning
  `nil` would work equally well *here* and break the moment someone tested
  presence with `contains?`, so we match the oracle exactly.

  Asserts the types the way the SDK does, which means these are `*assert*`-gated
  and vanish under `:elide-asserts`. Fine: a non-string id is a programming
  error, and the assertion exists to name it at the call site rather than to
  defend the wire.

  `str/blank?` rather than `.trim`, which was the first thing written here and
  was wrong: `.trim` cuts at U+0020 while `blank?` asks `Character/isWhitespace`,
  so an id of `\"\\u2028\"` is blank to one and not the other. The oracle uses
  `blank?`, so we use `blank?` — the point of having an oracle is to stop making
  independent judgement calls about rules we did not write."
  [opts]
  (let [event-id (get opts id "")
        retry    (get opts retry-duration default-retry-duration)]
    (assert (string? event-id) "SSE event id must be a String")
    (assert (number? retry) "SSE retry duration must be a number")
    {id             (and (not (str/blank? event-id)) event-id)
     retry-duration (and (> retry 0) (not= retry default-retry-duration) retry)}))

;; -----------------------------------------------------------------------------
;; Layer 5 — the response headers
;; -----------------------------------------------------------------------------
;;
;; the header extraction. Three headers and one question the SDK never asks.

(def base-headers
  "The two headers every SSE response carries, whatever is in it.

  `Content-Type` is **bare**: `text/event-stream`, with no `; charset=utf-8`.
  Adding one is the obvious independent-implementation mistake and it is not
  harmless — the HTML spec defines `text/event-stream` as UTF-8 and tells user
  agents to ignore the parameter, so it says nothing, while
  `http-test/sse-round-trip` asserts exact equality and would fail."
  {"Cache-Control" "no-cache"
   "Content-Type"  "text/event-stream"})

(defn keep-alive?
  "Whether a response to `request` should carry `Connection: keep-alive`.

  The rule is **below** HTTP/1.1, not *at* it, and it is the one non-obvious
  thing in this layer. Datastar's cross-language ADR says to set the header for
  HTTP/1.1; the Clojure SDK deliberately does not, and it is right twice over —
  persistent connections are the default from 1.1 onward, so there the header is
  merely redundant, and in HTTP/2 and /3 it is **forbidden**: RFC 9113 §8.2.2
  lists `Connection` among the connection-specific fields a peer MUST treat as
  malformed, and RFC 9114 §4.2 repeats it. Sending it to an h2 client does not
  degrade the stream, it kills it. Following the ADR's text literally is
  therefore worse than ignoring it.

  Note the shape: a **comparison**, not a list of exempt versions. That is not
  terseness. `sse-test`'s negative control names HTTP/2 explicitly — the
  exception everyone remembers — and is thereby wrong for HTTP/3, which did not
  exist when that habit formed. An ordering rule covers the versions that have
  not shipped yet.

  A missing `:protocol` counts as below. `clojure.core/compare` already sorts
  `nil` before every string, so the explicit `nil?` clause is documentation
  rather than logic — kept because \"nil compares less than everything\" is
  exactly the kind of fact that is silent when you have it backwards. The oracle
  (`sdk-sse/add-keep-alive?`) is written the same way."
  [request]
  (let [protocol (:protocol request)]
    (or (nil? protocol)
        (neg? (compare protocol "HTTP/1.1")))))

(defn- accept-encoding-qs
  "One `Accept-Encoding` field value as `{coding q}`, codings lower-cased and an
  absent or unparseable `q` defaulting to 1.

  Entries with no coding are dropped, which is what makes an **empty** field
  value an empty map rather than a map with an empty key — the case that decides
  `acceptable-encoding?`'s third spelling of refusal."
  [^String field]
  (into {}
        (for [entry (str/split field #",")
              :let  [[coding & params] (map str/trim (str/split entry #";"))
                     q (some (fn [^String p]
                               (let [p (str/lower-case p)]
                                 (when (str/starts-with? p "q=")
                                   (parse-double (subs p 2)))))
                             params)]
              :when (not (str/blank? coding))]
          [(str/lower-case coding) (or q 1.0)])))

(defn acceptable-encoding?
  "Whether `request` will accept a response body compressed with `encoding`
  (`\"gzip\"`, ...). RFC 9110 §12.5.3.

  **This function has no counterpart in the SDK, and it is why the header extraction exists.**
  `adapter/common/headers` derives `Content-Encoding` from the write profile
  alone; it takes the request only to check the protocol version, so it never
  asks whether the client can decode what it is about to be sent. Not fixable
  from outside — see `dj.web.datastar/negotiated-write-profile`, which is
  the other half.

  The rule is narrower than it first looks, and the extraction design's plan had it wider:
  **silence is permission.** An absent `Accept-Encoding` means *any* coding is
  acceptable, so gzipping a client that never asked is legal, if unfriendly.
  What is not legal is gzipping a client that **refused**, and refusal has three
  spellings:

      Accept-Encoding: identity     ; gzip not listed, and no wildcard
      Accept-Encoding: gzip;q=0     ; listed and explicitly rejected
      Accept-Encoding:              ; empty: no coding at all is wanted

  `*` stands in for anything not named, so `*;q=0` refuses everything unlisted
  while `gzip, *;q=0` still allows gzip. Qvalues are read **only** for the `q=0`
  test: we have exactly one coding on offer, so there is no preference to rank,
  and `gzip;q=0.001` is a yes.

  A `nil` request, or one with no headers, is the absent case — acceptable.

  Only ever asked about a real coding. `identity` — which RFC 9110 says is
  always acceptable unless explicitly refused — is spelled `nil` on our side (no
  encoding at all) and never reaches here."
  [request encoding]
  (if-let [field (get-in request [:headers "accept-encoding"])]
    (let [qs (accept-encoding-qs field)
          q  (get qs (str/lower-case encoding) (get qs "*"))]
      (boolean (and q (pos? q))))
    true))

(defn headers
  "The response headers for an SSE stream: `base-headers`, plus
  `Connection: keep-alive` when `keep-alive?` says so, plus `Content-Encoding`
  when `encoding` is non-nil. `extra` is merged **last**, so a caller can
  override any of them — including the ones it should think twice about.

  `encoding` is an argument rather than something derived here, and that is the
  shape change the header extraction is. The SDK's `ac/headers` derives it from the write
  profile, which makes this header a *report* of a decision taken elsewhere with
  less information than it needed: the profile also decides whether the output
  stream gets wrapped in a `GZIPOutputStream`, and those two must never
  disagree. Taking the coding as a parameter lets the decision be made once,
  against the request, by whoever owns both halves —
  `dj.web.datastar/negotiated-write-profile`."
  [request encoding extra]
  (-> base-headers
      (cond-> (keep-alive? request) (assoc "Connection" "keep-alive")
              encoding              (assoc "Content-Encoding" encoding))
      (merge extra)))

;; -----------------------------------------------------------------------------
;; Frame assembly
;; -----------------------------------------------------------------------------

(defn write-event!
  "Append one SSE event to `appendable` (a StringBuilder, a BufferedWriter, ...)
  and return it. Same signature as `starfederation.datastar.clojure.api.sse/
  write-event!`, and byte-identical to it — `sse-test` asserts that over the
  full option matrix.

  The frame, in exactly this order:

    1. `event: <event-type>\\n`      always
    2. `id: <id>\\n`                 only when `id` is truthy
    3. `retry: <n>\\n`               only when `retry-duration` is truthy
    4. `data: <line>\\n`             once per data line
    5. `\\n`                         the blank line that ends the event

  \"Truthy\", not \"present\": `normalize-event-opts` returns a map that always
  has both keys and sets a dropped one to **`false`** — so that is the shape of
  the *default* call, and a `contains?`/`some?` test here would put `id: false`
  on the wire for every ordinary event.

  Unlike the SDK we do NOT wrap append failures in `ex-info`. The SDK's wrapping
  costs more than it explains: the only thing that realistically throws here is
  the socket, and an `IOException` wrapped in an `ex-info` no longer satisfies
  the `(instance? IOException e)` test in `ac/default-on-exception`, so a
  disconnected client would be rethrown as an error instead of quietly closing
  the generator. (Latent in the SDK rather than live: with the temp-buffer write
  profiles the appends land in a StringBuilder and the socket is only touched
  afterwards — it bites the buffered-writer profiles, which write through.)"
  ^Appendable [^Appendable appendable event-type data-lines opts]
  (let [event-id (get opts id)
        retry    (get opts retry-duration)]
    (doto appendable
      (.append "event: ")
      (.append (str event-type))
      (.append "\n"))
    (when event-id
      (doto appendable
        (.append "id: ")
        (.append (str event-id))
        (.append "\n")))
    (when retry
      (doto appendable
        (.append "retry: ")
        (.append (str retry))
        (.append "\n")))
    (doseq [line data-lines]
      (doto appendable
        (.append "data: ")
        (.append (str line))
        (.append "\n")))
    (.append appendable "\n")
    appendable))

(defn write-comment!
  "Append an SSE comment frame — `: <text>` and the blank line — and return
  `appendable`. A comment is a no-op for the client: it is not an event, fires
  no listener, and patches nothing. It exists to put bytes on an idle socket so
  a dead peer is discovered by a failed write rather than by silence.

  **This is the capability that owning layer 3 buys**, and the reason that slice
  went first. The SDK structurally cannot emit one: every path into a generator
  goes through `p/send-event!`, which writes `event: <type>` before anything
  else. A heartbeat through the SDK is therefore a no-op `patch-signals!` —
  about 40 bytes, and a real `datastar-patch-signals` event the browser has to
  process. This is ~10 bytes and nothing to process. the subscription
  registry is what will call it.

  `text` must not contain a newline: an SSE comment is one line, so an embedded
  `\\n` would end the comment and inject whatever followed as a stream field.
  Callers pass a literal (`\"ping\"`); this does not defend against them."
  ^Appendable [^Appendable appendable ^String text]
  (doto appendable
    (.append ": ")
    (.append text)
    (.append "\n\n")))
