(ns dj.web.datastar.wire
  "**Letters.** The Datastar wire semantics: which data lines an operation
  produces, in which order, and how a payload string becomes N of them. It
  produces a vector of strings and has no idea that an SSE frame exists. Plus
  the one thing that travels the other way — `get-signals`, which says where on
  an incoming request Datastar puts the client's store (layer 6).

  Its counterpart is `dj.web.sse` (the envelopes), and the two do not know about each
  other — the value passed between them is a plain vector of strings, which is
  what lets either one independently be ours or the SDK's:

      semantic op          data lines              frame bytes          socket
      patch-elements  ->   [\"mode append\"    ->   event: ...\\n     ->   OutputStream
      html + opts          \"elements <div>\"]      data: mode append\\n
                                                  data: elements ...\\n
                                                  \\n
      layer 2 (HERE)       layer 3                 layer 4
      \"the letters\"        dj.web.sse         dj.web.datastar

  **This namespace must never require `starfederation.*`, nor `dj.web.sse`.**
  It is pure: string (or a request map) in, plain values out; no protocol, no
  IO, no lock — `get-signals` hands back the request's `:body` stream without
  reading it, and the JSON parse belongs to the layer above. A transport such as
  `dj.web.datastar.reference` composes these values with SSE and a socket.

  The owned element surface is intentionally small: `selector` and `mode`, plus
  the payload lines. `useViewTransition`, `viewTransitionSelector`, `namespace`,
  and the signal option `onlyIfMissing` are rejected on presence instead of
  silently disappearing. Incoming signals are returned from the correct request
  location without doing IO here.

  Tiny as it is, this is where being wrong is *silent*, and it contains the
  sharpest lesson in the plan — see `split-data-lines`."
  (:require [clojure.string :as str]))

;; -----------------------------------------------------------------------------
;; Layer 1 — the literals
;; -----------------------------------------------------------------------------
;;
;; Upstream's `consts.clj` carries "auto-generated by
;; Datastar. DO NOT EDIT" — these strings are generated from the spec across
;; every language SDK at once, while ours are hand-written, so they are the one
;; part of this plan with a *recurring* cost. The mitigation is that
;; `wire-test/datastar-literals-match-the-sdk` asserts each one `=` the SDK's:
;; the jar stops being a dependency and becomes a spec tracker, and a
;; `clj -Sforce -M:test` after a version bump tells us the wire moved.

(def event-type-patch-elements "datastar-patch-elements")
(def event-type-patch-signals  "datastar-patch-signals")

(def elements-dataline-literal "elements ")
(def signals-dataline-literal  "signals ")

(def datastar-key
  "The query-param name the client puts its signals JSON under, for the methods
  that have no body. A **String** key, not a keyword — see `get-signals`."
  "datastar")

(def datastar-request-header
  "The header the client sets on every action-issued request. **Lower-case**,
  because that is the shape `dj.web.http/request-headers` produces — see
  `datastar-request?`.

  The one literal here with no counterpart in the SDK's `consts.clj`: upstream
  inlines the string in `api.clj` rather than generating it, so unlike its four
  neighbours nothing pins this one to the spec. `wire-test` diffs the
  *function* instead, which is the best oracle available for it."
  "datastar-request")

;; The five element option keys and the signals one. `selector` and `patch-mode`
;; are owned below; the remainder exist so unsupported input can be named.
(def selector                 :d*.elements/selector)
(def patch-mode               :d*.elements/patch-mode)
(def use-view-transition      :d*.elements/use-view-transition)
(def view-transition-selector :d*.elements/view-transition-selector)
(def element-namespace        :d*.elements/namespace)
(def only-if-missing          :d*.signals/only-if-missing)

;; -----------------------------------------------------------------------------
;; Layer 6 — the request side
;; -----------------------------------------------------------------------------

(defn get-signals
  "The client's signals as Datastar put them on `request`, **unparsed**: a
  String for `GET`/`DELETE`, the `:body` InputStream for everything else, `nil`
  if there are none. Same rule and same return types as
  `starfederation.datastar.clojure.api/get-signals`, which `wire-test` diffs
  over the method matrix. Parsing is `dj.web.datastar/signals`.

  Two return types rather than one because the split is not ours to make: a
  `GET` has no body, so the store rides in a query param and arrives already
  decoded as a String, while `POST`/`PUT`/`PATCH` carry it as bytes we have not
  read yet. Slurping the stream here would make this layer do IO and would
  consume a one-shot stream on behalf of a caller that might not want it.

  **This is the request-side extraction, and it is the seam where a non-ring server diverges in
  silence** — which is the only reason a three-line function got its own slice.
  We are not ring: `dj.web.http/query-params` is ours, and this function
  asserts that it parsed the query string the way ring would. Get the collision
  rule wrong (ring: one occurrence is a String, two make a **vector**) and a
  duplicated `datastar` param hands a vector to `json/read-str`, which reports a
  type error about a value nobody wrote. Get the decoding wrong — split a
  decoded query string rather than the raw one — and a `%26` inside the JSON
  ends the param early, so the signals are truncated rather than absent.
  `http-test/signals-in` drives a real `@get`-shaped URL through the server for
  exactly this reason; the differential here only pins the lookup.

  String key, not keyword: that is ring's shape for `:query-params`, and it is
  where the SDK looks. Keywordizing query params would be a second convention
  for the same map."
  [request]
  (case (:request-method request)
    (:get :delete) (get-in request [:query-params datastar-key])
    (:body request)))

(defn datastar-request?
  "True when `request` came from a Datastar action (`@get`, `@post`, ...) rather
  than a plain page load — useful for handlers that serve both.

  **Exact** equality against `\"true\"`, not presence and not a case-insensitive
  compare, because that is the rule: the client sets the header to that literal,
  so anything else did not come from the client we are talking about. Two ways
  our own HTTP layer can produce an \"anything else\" worth knowing about:

  - `dj.web.http/request-headers` **lower-cases** every header name (ring's
    shape), which is why the key here is lower-case. Look for `Datastar-Request`
    and every action request reads as a page load.
  - it also **comma-joins** a header that arrives more than once, so a doubled
    header gives `\"true,true\"` — false here, correctly. A `str/includes?`
    would have said true, and would also have said true for `\"untrue\"`."
  [request]
  (= "true" (get-in request [:headers datastar-request-header])))

;; -----------------------------------------------------------------------------
;; The splitter
;; -----------------------------------------------------------------------------

(defn split-data-lines
  "Split `text` into SSE data lines the way the wire requires, using Java's
  `String.lines()`.

  **`.lines()`, not `clojure.string/split-lines`, and this is the finding the
  whole slice exists to produce.** The two agree on `\\n` and on `\\r\\n` and
  disagree on a **lone `\\r`**:

      (split-data-lines \"a\\rb\")            => [\"a\" \"b\"]     ; .lines()
      (str/split-lines  \"a\\rb\")            => [\"a\\rb\"]      ; passes it through

  A lone `\\r` is a line terminator per the SSE spec, so `.lines()` is right and
  `split-lines` ships a `\\r` inside a `data:` line. The browser's parser then
  ends the field at the `\\r` and reads the remainder — `b` above — as the *name*
  of the next field, which it does not recognise, so it **silently discards it**.
  The element truncates. No exception is thrown anywhere, on either side.

  That is not a hypothetical: a lone `\\r` arrives in every string we did not
  author — var docstrings, ledger content, fetched pages — and the original namespace-browser example
  renders docstrings straight into a `<pre>`. We would have shipped it, and the
  symptom (some panels truncate, sometimes) reads as a rendering bug, not a wire
  bug.

  There are two more divergences, and the third was **not** predicted by the
  plan — it fell out of running `split-lines` through the differential harness
  as a negative control (3 of 18 payloads diverge, not 1):

  - `\"\"`: `.lines()` yields `[]`, `split-lines` yields `[\"\"]`. This is why a
    blank payload must emit no `elements` line at all rather than an empty one
    — see `->patch-elements`.
  - **trailing blank lines**: `split-lines` is `(str/split s #\"\\r?\\n\")`, and
    `split` with no limit **drops trailing empty strings**. So `\"a\\n\\n\"`
    becomes `[\"a\"]` there and `[\"a\" \"\"]` here. Rendered HTML and markdown
    end with a newline constantly, so this fires far more often than the `\\r`
    case; it is just less dramatic — you lose a trailing blank line inside a
    `<pre>` rather than truncating an element.

  Returns a vector so the result is a value with no stream semantics attached."
  [prefix ^String text]
  (into [] (map #(str prefix %)) (iterator-seq (.iterator (.lines text)))))

;; -----------------------------------------------------------------------------
;; The deliberately small option surface
;; -----------------------------------------------------------------------------

(def ^:private element-opt-keys
  (array-map selector                 "selector"
             patch-mode               "mode"
             use-view-transition      "useViewTransition"
             view-transition-selector "viewTransitionSelector"
             element-namespace        "namespace"))

(def ^:private signals-opt-keys
  (array-map only-if-missing "onlyIfMissing"))

(def ^:private sse-opt-keys
  #{:d*.sse/id :d*.sse/retry-duration})

(def ^:private patch-modes
  #{"remove" "outer" "inner" "replace" "prepend" "append" "before" "after"})

(defn- reject-unknown-opts! [opts known op]
  (when-let [ks (not-empty (filterv #(not (contains? known %)) (keys opts)))]
    (throw (ex-info (str "dj.web.datastar.wire/" op " received unknown option "
                         (str/join ", " (map pr-str ks)))
                    {:unknown ks :op op}))))

(defn- validate-patch-mode! [mode op]
  (when-not (contains? patch-modes mode)
    (throw (ex-info (str "dj.web.datastar.wire/" op
                         " received unsupported patch mode " (pr-str mode))
                    {:patch-mode mode :supported patch-modes :op op}))))

(defn- reject-unsupported-opts!
  "Throw if `opts` carries a layer-2 option this stack does not implement.

  The alternative — ignore it — is the exact failure mode this layer is prone
  to: an omitted option changes UI behavior without an error.

  Rejects on *presence*, not truthiness, so an unsupported nil cannot appear to
  have been accepted."
  [opts known op]
  (when-let [ks (not-empty (filterv #(contains? opts %) (keys known)))]
    (throw (ex-info (str "dj.web.datastar.wire/" op " does not implement "
                         (str/join ", " (map known ks)))
                    {:unsupported ks :op op}))))

(def ^:private unsupported-element-opt-keys
  (select-keys element-opt-keys
               [use-view-transition view-transition-selector element-namespace]))

;; -----------------------------------------------------------------------------
;; The two operations
;; -----------------------------------------------------------------------------

(defn ->patch-elements
  "Data lines for a `datastar-patch-elements` event: one `elements <line>` per
  line of `elements`. Same signature and same output as
  `starfederation.datastar.clojure.api.elements/->patch-elements` on the subset
  we implement (`selector` and `mode`), which `wire-test` asserts over its full
  cross-product.

      (->patch-elements \"<div>x</div>\" {})   => [\"elements <div>x</div>\"]
      (->patch-elements \"a\\nb\" {})           => [\"elements a\" \"elements b\"]
      (->patch-elements \"\" {})               => []

  **A blank payload emits nothing, not an empty line.** Whitespace-only counts
  as blank, so `\" \\n \"` is `[]` too. This is the rule that makes the SDK's
  `remove-element!` work: it is `patch-elements!` with an empty body and
  `mode remove`, and an `elements ` line with nothing after it would be a patch
  of the empty string rather than a removal.

  Note the composition with `split-data-lines`: for a *non*-blank payload the
  blank check is already redundant with `.lines()` returning `[]` on `\"\"` — but
  only for `\"\"` exactly. `\"  \"` is non-empty to `.lines()` and blank to
  `str/blank?`, and the SDK suppresses it. Two rules that look like one."
  [^String elements opts]
  (reject-unknown-opts! opts
                        (into sse-opt-keys (keys element-opt-keys))
                        "patch-elements!")
  (reject-unsupported-opts! opts unsupported-element-opt-keys "patch-elements!")
  (let [selector-value (get opts selector "")
        mode-value     (get opts patch-mode "outer")]
    (assert (string? selector-value) "Datastar selector must be a String")
    (assert (string? mode-value) "Datastar patch mode must be a String")
    (validate-patch-mode! mode-value "patch-elements!")
    (cond-> []
      (not (str/blank? selector-value)) (conj (str "selector " selector-value))
      (and (not (str/blank? mode-value)) (not= "outer" mode-value))
      (conj (str "mode " mode-value))
      (not (str/blank? elements))
      (into (split-data-lines elements-dataline-literal elements)))))

(defn ->patch-signals
  "Data lines for a `datastar-patch-signals` event: one `signals <line>` per line
  of the JSON text in `signals`. Same rules as `->patch-elements` — blank emits
  nothing, `.lines()` does the splitting.

      (->patch-signals \"{\\\"a\\\":1}\" {})   => [\"signals {\\\"a\\\":1}\"]

  The multi-line case is not an edge case to tolerate but the normal one for
  pretty-printed JSON, and it is why `signals` is a data line rather than a
  header: SSE has no way to carry a raw newline in a field, so every producer
  has to split. We take JSON as a **String**, not a map, for the same reason the
  SDK does — the caller owns the encoder (`clojure.data.json` here), and a map
  argument would silently pick one."
  [^String signals opts]
  (reject-unknown-opts! opts
                        (into sse-opt-keys (keys signals-opt-keys))
                        "patch-signals!")
  (reject-unsupported-opts! opts signals-opt-keys "patch-signals!")
  (if (str/blank? signals)
    []
    (split-data-lines signals-dataline-literal signals)))
