(ns dj.web.datastar.wire-test
  "Layer 2, the **letters**: `dj.web.datastar.wire` diffed against
  `starfederation.datastar.clojure.api.elements` / `.signals` over the shared
  matrix in `dj.web.wire-matrix` (which explains the method).

  Extraction stages asserted here: **2** — `->patch-elements` and `->patch-signals` for
  the no-options case, which is everything the original namespace-browser example and `http_test` call —
  and **4**, `get-signals` and `datastar-request?` — layer 6, the two functions
  in this namespace that run on the way *in*. The JSON parse that follows
  `get-signals` is layer 4's and is asserted in `http-test/signals-in`, over a
  real socket, because its failure mode is an HTTP status rather than a value.

  the extraction design  named the reason: `String.lines()` versus `clojure.string/split-lines` on a
  lone `\\r`. That prediction is stated as its own test rather than folded into
  the differential, and it comes in two parts:

  - `the-harness-catches-the-mistake-it-was-built-to-catch` runs the naive
    implementation through the matrix as a **negative control**. the differential harness's whole
    claim is that a diff against the oracle would have caught layer 2's silent
    mistakes; a matrix whose axes happen to miss the bug passes exactly as
    quietly as a correct implementation, so the claim is worth an assertion.
  - `split-lines-would-have-been-wrong` names each divergence. Running the
    control turned up **three**, not the one the plan predicted — the extra one
    is a trailing newline, and it fires more often than the `\\r` does."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [dj.web.datastar.wire :as wire]
            [dj.web.wire-matrix :as m]
            [starfederation.datastar.clojure.api :as sdk-api]
            [starfederation.datastar.clojure.api.common :as sdk-common]
            [starfederation.datastar.clojure.api.elements :as sdk-elements]
            [starfederation.datastar.clojure.api.signals :as sdk-signals]
            [starfederation.datastar.clojure.consts :as sdk-consts]))

;; -----------------------------------------------------------------------------
;; Layer 1 — the Datastar literals
;; -----------------------------------------------------------------------------

(deftest datastar-literals-match-the-sdk
  (testing "every hand-written literal equals its code-generated counterpart"
    ;; Upstream's `consts.clj` says "auto-generated by Datastar. DO NOT EDIT" —
    ;; these strings are generated from the spec across every language SDK at
    ;; once, so ours are the only hand-maintained copy in the world and this is
    ;; the only thing that would tell us the spec moved.
    (is (= sdk-consts/event-type-patch-elements wire/event-type-patch-elements))
    (is (= sdk-consts/event-type-patch-signals  wire/event-type-patch-signals))
    (is (= sdk-consts/elements-dataline-literal wire/elements-dataline-literal))
    (is (= sdk-consts/signals-dataline-literal  wire/signals-dataline-literal))
    (is (= sdk-consts/datastar-key              wire/datastar-key)))
  (testing "and the option keys we reject by name"
    (is (= sdk-common/selector                 wire/selector))
    (is (= sdk-common/patch-mode               wire/patch-mode))
    (is (= sdk-common/use-view-transition      wire/use-view-transition))
    (is (= sdk-common/view-transition-selector wire/view-transition-selector))
    (is (= sdk-common/element-namespace        wire/element-namespace))
    (is (= sdk-common/only-if-missing          wire/only-if-missing))))

;; -----------------------------------------------------------------------------
;; the wire extraction — the differential
;; -----------------------------------------------------------------------------

(deftest patch-elements-matches-the-sdk-on-every-owned-shape
  (testing "18 payloads crossed with selector and mode"
    (let [cases (filterv #(every? #{wire/selector wire/patch-mode}
                                  (keys (:opts %)))
                         m/element-cases)
          d (m/diffs cases
                     #(wire/->patch-elements (:elements %) (:opts %))
                     #(sdk-elements/->patch-elements (:elements %) (:opts %)))]
      (is (empty? d) (m/report d)))))

(deftest patch-signals-matches-the-sdk-on-every-payload
  (testing "8 JSON shapes, no options"
    (let [d (m/diffs m/signals-cases-no-opts
                     #(wire/->patch-signals (:signals %) (:opts %))
                     #(sdk-signals/->patch-signals (:signals %) (:opts %)))]
      (is (empty? d) (m/report d)))))

;; -----------------------------------------------------------------------------
;; The finding this slice exists to produce
;; -----------------------------------------------------------------------------

(defn- naive-split
  "What the obvious Clojure implementation of `split-data-lines` would be. Kept
  as an executable negative control rather than a comment: running it through
  the same matrix is what proves the harness is not vacuous, and it is how the
  trailing-newline divergence below was found — the plan predicted only the
  lone `\\r`."
  [prefix text]
  (mapv #(str prefix %) (str/split-lines text)))

(deftest the-harness-catches-the-mistake-it-was-built-to-catch
  (testing "swapping in `split-lines` diverges from the oracle on 3 of 18 payloads"
    ;; the differential harness's claim is that the differential matrix would have caught the
    ;; layer-2 mistakes. That claim is worth testing directly, because a matrix
    ;; whose axes happen to miss the bug passes just as quietly as a correct
    ;; implementation. These are the three, by label:
    ;;   :cr       "a\rb"    -> ["elements a\rb"]  vs ["elements a" "elements b"]
    ;;   :mixed    "a\nb\rc\r\nd"
    ;;   :trailing "a\n\n"   -> ["elements a"]     vs ["elements a" "elements "]
    (let [d (m/diffs m/element-cases-no-opts
                     #(if (str/blank? (:elements %))
                        []
                        (naive-split wire/elements-dataline-literal (:elements %)))
                     #(sdk-elements/->patch-elements (:elements %) (:opts %)))]
      (is (= #{:cr :mixed :trailing} (into #{} (map (comp :elements :label)) d))
          (str "the negative control found: "
               (pr-str (mapv :label d)))))))

(deftest split-lines-would-have-been-wrong
  (testing "`.lines()` and `split-lines` diverge on a lone \\r, and it is silent"
    ;; The defect we did not ship. A lone `\r` is a line terminator per the SSE
    ;; spec, so it MUST become a new `data:` line. Leave it inside one and the
    ;; browser ends the field at the `\r` and reads the rest as the *name* of an
    ;; unrecognised field, which it discards without a word: the element simply
    ;; truncates. Nothing throws on either side of the socket.
    ;;
    ;; This is not exotic input. A lone `\r` arrives in every string we did not
    ;; author — var docstrings, ledger content, fetched pages — and the original namespace-browser example
    ;; renders docstrings straight into a `<pre>`.
    (is (= ["elements a" "elements b"] (wire/->patch-elements "a\rb" {})))
    (is (= ["elements a\rb"] (naive-split "elements " "a\rb"))
        "what the obvious Clojure implementation would have produced"))
  (testing "and a trailing newline, which the plan did not predict"
    ;; `split-lines` is `(split s #\"\r?\n\")`, and `split` drops trailing empty
    ;; strings. Rendered HTML and markdown end in a newline constantly, so this
    ;; one fires far more often than the `\r` — it is just quieter, costing a
    ;; blank line inside a `<pre>` rather than truncating an element.
    (is (= ["elements a" "elements "] (wire/->patch-elements "a\n\n" {})))
    (is (= ["elements a"] (naive-split "elements " "a\n\n"))))
  (testing "and they agree everywhere a naive test would think to look"
    ;; Which is the point: `\n` and `\r\n` are what anyone writes a test for.
    (is (= (wire/->patch-elements "a\nb" {}) (naive-split "elements " "a\nb")))
    (is (= (wire/->patch-elements "a\r\nb" {}) (naive-split "elements " "a\r\nb")))))

(deftest blank-suppression-is-a-separate-rule-from-splitting
  (testing "a blank payload emits no line at all, not an empty one"
    ;; This is what makes the SDK's `remove-element!` work — it is
    ;; `patch-elements!` with an empty body and `mode remove`, and an `elements `
    ;; line with nothing after it would be a patch of the empty string rather
    ;; than a removal.
    (is (= [] (wire/->patch-elements "" {})))
    (is (= [] (wire/->patch-signals "" {}))))
  (testing "whitespace-only counts as blank, which splitting alone would not catch"
    ;; `.lines()` returns `[]` for `""` — so for that one input the blank guard
    ;; looks redundant. It is not: `"  "` and `"\n"` are both non-empty to
    ;; `.lines()` and blank to `str/blank?`, and the SDK suppresses both. Two
    ;; rules that look like one.
    (is (= [] (wire/->patch-elements "  " {})))
    (is (= [] (wire/->patch-elements "\n" {})))
    (is (= [] (wire/->patch-elements "\r" {})))
    (is (= ["elements "] (wire/split-data-lines wire/elements-dataline-literal "\n"))
        "the splitter on its own would have emitted the empty line")))

(deftest the-lines-are-what-we-think-they-are
  (testing "written from the Datastar spec, not from either implementation"
    ;; Two implementations can agree and both be wrong; the differential tests
    ;; are only as good as the literal ones next to them.
    (is (= ["elements <div>x</div>"] (wire/->patch-elements "<div>x</div>" {})))
    (is (= ["elements a" "elements b"] (wire/->patch-elements "a\nb" {})))
    (is (= ["elements a" "elements b"] (wire/->patch-elements "a\r\nb" {})))
    (is (= ["signals {\"a\":1}"] (wire/->patch-signals "{\"a\":1}" {})))
    (is (= ["signals {" "signals   \"a\": 1" "signals }"]
           (wire/->patch-signals "{\n  \"a\": 1\n}" {}))
        "pretty-printed JSON is the normal case, not an edge one"))
  (testing "a payload that looks like SSE syntax is content, never syntax"
    ;; Layer 3 adds `data: `; a payload is never parsed on the way out.
    (is (= ["elements data: not-a-field"] (wire/->patch-elements "data: not-a-field" {})))
    (is (= ["elements : not-a-comment"] (wire/->patch-elements ": not-a-comment" {})))))

;; -----------------------------------------------------------------------------
;; the request-side extraction — layer 6, the way back in
;; -----------------------------------------------------------------------------

(deftest get-signals-matches-the-sdk-on-every-method
  (testing "8 methods x 4 payload placements — including the mismatched ones"
    ;; The rule is a `case` over `(:get :delete)` with a default, so the cases
    ;; that matter are the ones where method and placement disagree: a `:get`
    ;; carrying a body must still read the query param (and answer nil when
    ;; there isn't one) rather than fall through to the body it does have.
    (let [d (m/diffs m/signals-request-cases
                     #(wire/get-signals (:request %))
                     #(sdk-signals/get-signals (:request %)))]
      (is (empty? d) (m/report d)))))

(defn- naive-get-signals
  "What the obvious Clojure implementation would be: *look in the query param,
  fall back to the body.* Kept as an executable negative control for the same
  reason `naive-split` is — a differential that only ever agrees has proven
  nothing about the axes it crosses."
  [request]
  (or (get-in request [:query-params "datastar"]) (:body request)))

(deftest the-method-axis-is-not-decoration
  (testing "`or` instead of a method `case` diverges on 14 of 32 requests"
    ;; The reason `signals-request-cases` crosses its two axes instead of
    ;; listing them. `or` looks equivalent — every request in an app carries its
    ;; payload in exactly one pocket, so the two agree on all 16 of those. They
    ;; part on the mismatched ones, and the direction matters: a `:get` with a
    ;; body reads that body under `or`, which is how a request with stale bytes
    ;; on it (or a proxy that adds some) turns into signals nobody sent.
    (let [d (m/diffs m/signals-request-cases
                     #(naive-get-signals (:request %))
                     #(sdk-signals/get-signals (:request %)))]
      (is (= 14 (count d)))
      (is (contains? (into #{} (map :label) d) {:method :get :payload :body})
          "the case that shows it is a `case`, not a fallback"))))

(deftest get-signals-reads-the-pocket-the-method-implies
  (testing "written from the Datastar spec, not from either implementation"
    ;; `@get`/`@delete` have no body, so the store rides in a query param;
    ;; everything else carries it as bytes. Two return types, one function —
    ;; the split is Datastar's, not a convenience of ours.
    (let [json "{\"query\":\"dj http\"}"]
      (is (= json (wire/get-signals {:request-method :get
                                     :query-params {"datastar" json}})))
      (is (= json (wire/get-signals {:request-method :delete
                                     :query-params {"datastar" json}})))
      (is (nil? (wire/get-signals {:request-method :get :query-params {}}))
          "no signals at all is nil, not a parse error")
      (is (nil? (wire/get-signals {:request-method :get
                                   :query-params {"other" json}}))
          "and it is the `datastar` key specifically")))
  (testing "a body method returns the stream itself, unread"
    ;; Layer 6 must not do IO: slurping here would consume a one-shot stream on
    ;; behalf of a caller that may not want it, and would put a blocking read in
    ;; a namespace whose invariant is that it has none.
    (let [body (java.io.ByteArrayInputStream. (.getBytes "{\"a\":1}" "UTF-8"))]
      (is (identical? body (wire/get-signals {:request-method :post :body body})))
      (is (= "{\"a\":1}" (slurp body)) "still unread")))
  (testing "the query param is a STRING key, which is ring's shape"
    ;; Not a keyword: this is the seam where `dj.web.http/query-params` —
    ;; ours, not ring's — has to agree with where the SDK looks. Keywordizing
    ;; would be a second convention for the same map.
    (is (nil? (wire/get-signals {:request-method :get
                                 :query-params {:datastar "{\"a\":1}"}})))))

(deftest datastar-request?-matches-the-sdk-on-every-header-value
  (testing "exact equality with \"true\" — the near misses are the point"
    (let [d (m/diffs m/datastar-request-cases
                     #(wire/datastar-request? (:request %))
                     #(sdk-api/datastar-request? (:request %)))]
      (is (empty? d) (m/report d)))))

(deftest datastar-request?-is-exact-equality-and-that-matters-twice
  (testing "written from the rule, not from either implementation"
    (is (true? (wire/datastar-request? {:headers {"datastar-request" "true"}})))
    (is (false? (wire/datastar-request? {:headers {}}))))
  (testing "our http layer lower-cases header names, so the key must be too"
    ;; `dj.web.http/request-headers` lower-cases every name (ring's shape).
    ;; Looking for `Datastar-Request` would read every action request as a page
    ;; load — silently, since a page load is a legitimate answer.
    (is (= "datastar-request" wire/datastar-request-header))
    (is (false? (wire/datastar-request? {:headers {"Datastar-Request" "true"}}))
        "which is what an already-lower-cased map means"))
  (testing "and it comma-joins a repeated header, which exact equality rejects"
    ;; A doubled header gives "true,true". `str/includes?` would have said true
    ;; here — and would also have said true for "untrue".
    (is (false? (wire/datastar-request? {:headers {"datastar-request" "true,true"}})))
    (is (false? (wire/datastar-request? {:headers {"datastar-request" "untrue"}})))
    (is (false? (wire/datastar-request? {:headers {"datastar-request" "TRUE"}})))))

;; -----------------------------------------------------------------------------
;; The deliberately unsupported remainder
;; -----------------------------------------------------------------------------

(deftest unimplemented-options-throw-instead-of-vanishing
  (testing "every unsupported layer-2 option key is refused by name"
    ;; Ignoring one does not error; it merely changes UI behavior silently.
    (doseq [k [wire/use-view-transition wire/view-transition-selector
               wire/element-namespace]]
      (is (thrown? clojure.lang.ExceptionInfo
                   (wire/->patch-elements "<div>x</div>" {k "whatever"}))
          (str "expected " k " to be refused")))
    (is (thrown? clojure.lang.ExceptionInfo
                 (wire/->patch-signals "{\"a\":1}" {wire/only-if-missing true}))))
  (testing "presence is what is refused, not truthiness"
    ;; A present unsupported key is rejected even when its value would produce
    ;; no line. Otherwise adding an option can silently change nothing.
    (is (thrown? clojure.lang.ExceptionInfo
                 (wire/->patch-elements "<div>x</div>"
                                       {wire/use-view-transition nil}))))
  (testing "SSE event options pass through untouched"
    ;; `id`/`retry` live in the same opts map and belong to layer 3. Refusing
    ;; them here would break `ds/patch-elements!`, which hands one map to both.
    (is (= ["elements <div>x</div>"]
           (wire/->patch-elements "<div>x</div>" {:d*.sse/id "e1"
                                                  :d*.sse/retry-duration 500})))))
